services:
  dev:
    arborist:
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
    audit:
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
    fence:
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
  sbx:
    arborist:
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
    audit:
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"
    fence:
      - Effect: "Allow"
        Action:
          - "s3:ListAllMyBuckets"
        Resource: "*"


